version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mybookstore
      POSTGRES_USER: mybookstore_user
      POSTGRES_PASSWORD: mybookstore_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=mybookstore
      - DATABASE_USER=mybookstore_user
      - DATABASE_PASSWORD=mybookstore_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
